Pick up ables
KalleLeskinen/nanomachines-but-micro pull request #18
Opened 2020-10-27 17:17 UTC by jnnuu

tässä branchissa on ammuslaatikko ja alkeellisia miinoja, sekä kahden pelaajan välillä sekoilevaan kameraan fix, jolloin pelaajat ohjaavat vain omia autoja. (tämä olisi hyvä ollut tehtynä omaan branchiinsä, mutta myöhästä tässä vaiheessa...)

miinat (ja raketit) vaativat vielä töitä, mutta eivät ole välttämättömiä tälle viikolle. miskan kanssa tultiin tulokseen että pelin core loop on hyvä saada toimimaan tällä viikolla. 

Pull request kamera fixin takia. jos olet tehnyt jo korjauksia pelaajien kameroihin, niin vastaa tähän niin katsotaan mitä asialle voidaan tehdä.

2020-10-27 17:27 UTC, jnnuu commented
Conflicting files:
lisäsin Car1_Torinolle MineSpawnerin ja CameraPos (molemmat empty game objecteja).  
Update VehicleController.cs => muutin `rig.usegravity =  true`, ei toivottua vaikutusta, committasin viimeisenä takaisin alkuperäiseen arvoon (false)

2020-10-28 08:51 UTC, KalleLeskinen requested changes
[REDACTED]

2020-10-28 08:54 UTC, KalleLeskinen requested changes
Siirrä .gitignore /Builds kansioon ja vaihda yksittäisten tiedostojen sijaan pelkästään
**StartFinishWin/** niin Ignoraa koko kansion

2020-10-28 08:59 UTC, closed without merging

2020-10-28 08:59 UTC, KalleLeskinen commented
Mergetty.